### ISSUE TITLE
The step of compute_rnn function in rnn.c

### ISSUE THREAD

**Issue by xyx361100238** [jzi040941/PercepNet#14]
Dear Noah, 
Sorry to trouble you again.

Why is the input parameter of the first GRU layer  is not **second_conv1d_out** but **convout_buf**,I was confused all the places use **convout_buf** as input.

Another:
`
#define MAX_NEURONS 128

  //concat for rb gru
  for (i=0;i<MAX_NEURONS;i++) rb_gru_input[i] = rnn->convout_buf[i];
  for (i=0;i<MAX_NEURONS;i++) rb_gru_input[i+MAX_NEURONS] = rnn->gru3_state[i];
  compute_gru(rnn->model->rb_gru, rnn->rb_gru_state, rb_gru_input);
`
This length is inconsistent with the training script

**Comment by jzi040941** [comment]
I thought I have to make buffer my self but the buffer is already implemented on nnet.cpp
I will remove that soon
