### ISSUE TITLE
Out of bound in erb_band->nfftborder[i+1]?

### ISSUE THREAD

**Issue by cookcodes** [jzi040941/PercepNet#16]
ERBBand *erb_band = new ERBBand(WINDOW_SIZE, NB_BANDS-2, 0/*low_freq*/, 20000/*high_freq*/);

void compute_band_energy(float *bandE, const kiss_fft_cpx *X) {
  int i;
  float sum[NB_BANDS] = {0};
  for (i=0;i<NB_BANDS;i++)
  {
    int j;
    int band_size;
    band_size = (erb_band->nfftborder[i+1]-erb_band->nfftborder[i]);    

Here, when i is NB_BANDS-1, then erb_band->nfftborder[i+1] will access erb_band->nfftborder[NB_BANDS], 
and in class ERBBand, the size of nfftborder is NB_BANDS

**Comment by cookcodes** [comment]
sum[i+1] in compute_band_energy() has the same bug

**Comment by jzi040941** [comment]
Hi, @cookcodes 
Thanks for reporting bug!
I fixed it on commit 57465e0
