### ISSUE TITLE
Hi，the questions of make -j 

### ISSUE THREAD

**Issue by zqlsnr** [jzi040941/PercepNet#19]
![image](https://user-images.githubusercontent.com/83391979/128680843-e187201c-e313-4dce-a9eb-c65ed9d615a0.png)

**Comment by jzi040941** [comment]
can you send me the above error message too,
I think it's because you don't have nnet_data.cpp

**Comment by zqlsnr** [comment]
Thanks! I solve this problem by upgrading gcc to 7.3, but I meet a new problem when execute "make -j" ？
![image](https://user-images.githubusercontent.com/83391979/128799548-447a762d-71c3-40fa-b541-789e015b7d17.png)

**Comment by jzi040941** [comment]
error occur when nnet_data.cpp is not exist
I didn't consider in case when there's no nnet_data.cpp which is generated by dump_percepnet.py
I fixed CMakeLists.txt on commit beb518f
now you can do "make -j" whether you have nnet_data.cpp or not
Thanks for letting me know the error.

**Comment by zqlsnr** [comment]
Hi, when I am training, the loss appear nan. Tha clean data is VCTK 28speak + 56speak,  the noise data is DEMAND. I merged into one large clean pcm and noise pcm.
![image](https://user-images.githubusercontent.com/83391979/129354409-f1838c6c-a197-418f-8d44-b67e28d25564.png)

**Comment by jzi040941** [comment]
Maybe you can fix nan problem refer to #22 !

**Comment by mehdi-zn** [comment]
Hi, encountered the following issues:
- Step 3: "segmentation fault (core dumped)"
- Step 5: No "/bin/src/percepNet_run" exist 
Thanks in advance!

**Comment by mehdi-zn** [comment]
Hi, encountered the following issues:

Step 3: "segmentation fault (core dumped)"
Step 5: No "/bin/src/percepNet_run" exist
Thanks in advance!

**Comment by jzi040941** [comment]
> Hi, encountered the following issues:
> 
> Step 3: "segmentation fault (core dumped)" Step 5: No "/bin/src/percepNet_run" exist Thanks in advance!

Hi, sorry for late reply
Could you tell me more specific information.
Did you type command for Step 3 like below?
` bin/src/percepNet sampledata/speech/speech.pcm sampledata/noise/noise20db.raw 4000 test.output `

Inference is step7, furthermore you cannot run step 7 if you don't have nnet_data.h which is generated on step 4,5,6.

**Comment by mehdi-zn** [comment]
> Could you tell me more specific information.
> Did you type command for Step 3 like below?

Thanks for reply. Yes I used commands. When typing command cmake .. I get the following warning: "nnet_data.cpp is not exist. Do not generate inference executable..." Then, when running bin/src/percepNet sampledata/speech/speech.pcm sampledata/noise/noise20db.raw 4000 test.output I got the Segmentation fault error.

**Comment by jzi040941** [comment]
use this command instead

```
bin/src/percepNet sampledata/speech/speech.pcm sampledata/noise/noise.pcm 4000 test.output
```

noise20db.raw is not exist in this repo that's why you get error message segmentation fault
