### ISSUE TITLE
The step of pitch filtering

### ISSUE THREAD

**Issue by aaronhsueh0506** [jzi040941/PercepNet#20]
Hi Noah,

I have been working on the PercepNet project recently, and I read the code in _denoise.cpp_.
I am not sure the code about "comb filtering" below:

`for (k=-COMB_M;k<COMB_M+1; k++){`
`    for (i=0;i<WINDOW_SIZE;i++)`
`      p[i] += st->comb_buf[COMB_BUF_SIZE-FRAME_SIZE*(FRAME_LOOKAHEAD)-WINDOW_SIZE-pitch_index*k+i]*common.comb_hann_window[k+COMB_M];
  } `

I was wondering that the pitch needs to compute with the previous frames and how it works?
Thank you!

**Comment by jzi040941** [comment]
there is code buffering input to comb_buf on denoise.cpp L350~L351
```
  RNN_MOVE(st->comb_buf, &st->comb_buf[FRAME_SIZE], COMB_BUF_SIZE-FRAME_SIZE);
  RNN_COPY(&st->comb_buf[COMB_BUF_SIZE-FRAME_SIZE], in, FRAME_SIZE);
```

so comb_buf will have previous and forward both frame

**Comment by aaronhsueh0506** [comment]
Hi Noah,

I convert the filter to the time sequence is 
![228382267_247401813868846_6200234835969266223_n](https://user-images.githubusercontent.com/58929071/128883839-abc9e99f-d068-44ab-b71e-aa1afac3fc5f.png).
I was wondering that is the p[i] does the time-domain convolution? Because I am not sure why need to run the second for loop(i=0~480).

Thanks

**Comment by jzi040941** [comment]
![image](https://user-images.githubusercontent.com/10007781/128888709-12cf1b23-a43b-4383-8110-235114d7d6fa.png)
we are processing for one window and it's size is 960 on this project

and pitch filtering is working like image above
that's why we need second loop

**Comment by aaronhsueh0506** [comment]
Thanks, Noah! But if T is not equal to 480, I am still confused. 
If T <480, will the processed frames overlap as shown in the figure below?

![224071037_1288470011608229_2202353118875704202_n](https://user-images.githubusercontent.com/58929071/128891153-53402a2d-6c83-4328-9a19-aa663d690989.png)
