### ISSUE TITLE
about power_noise_attenuation

### ISSUE THREAD

**Issue by zoulingqi** [jzi040941/PercepNet#27]
I'm curious about the calculation of power_noise_attenuation and I can't find the calculation formula of this value in the paper.Can you tell me why I can get this value as in your code?

**Comment by jzi040941** [comment]
![image](https://user-images.githubusercontent.com/10007781/141751926-59db4ce2-71d7-4be0-b295-7c1611ad2778.png)
In paper it's mentioned like above. it's used for calculating pitch coherence of estimated  periodic signal.

**Comment by zoulingqi** [comment]
thank you for your explanation!
