### ISSUE TITLE
Pitch filter output is not good

### ISSUE THREAD

**Issue by rameshkunasi** [jzi040941/PercepNet#3]
I have verified the pitch filter output, I didn't observe noise reduction after pitch filter and also speech was distorted in pitch filter output

**Comment by jzi040941** [comment]
Thanks for your verification.
Actually I revised pure Rnnoise comb filter to fit in PercepNet. 
Rnnoise use only one period but in PercepNet they use -m to m tap.
So I made another buffer (much larger than pitch_buf) and hann_window for comb filtering
there is some error on correlation term in x. It should be buffer[m-th frame delay] but it was not.
now I fixed it. could you check it agian please.

**Comment by rameshkunasi** [comment]
I verified with the new changes but no improvement

**Comment by jzi040941** [comment]
how about speech distortion. Is it still remaining?

**Comment by rameshkunasi** [comment]
Speech distortion is not observed, noise reduction also not observed. I am
not observing difference to input and output

**Comment by jzi040941** [comment]
there is some heuristic pitch filtering strength control on rnnoise version

try temporarily change the code to pass heuristic control
denoise.cpp :: 394
frame_synthesis(st, out, **X**); -> frame_synthesis(st, out, **P**);

maybe you can get a pure comb filtered output.
In my case it slightly deviate white noise.
