### ISSUE TITLE
about window_size

### ISSUE THREAD

**Issue by zoulingqi** [jzi040941/PercepNet#30]
hello,
I'm confused about window_size in the training file.Why do you reshape the input data from (2000,138) to (2000/window_size,window_size,138)?Can window_size take any value?

**Comment by zoulingqi** [comment]
i find that conv1 need a 3-dimensional input for 3-dimensional weight [512,128,5],but i set window_size to “1” and the code still works.Is this ok that i set window_size to 1?

**Comment by jzi040941** [comment]
Hi,
I think that you are using previous run.sh code, I've update kaldi style run.sh tool which is easy to understand how to use this framework
on new version I've changed name window_size to train_length_size on h5dirdataset, cause window_size might be confused with stft window_size
train_length_size is the same as sequence size when you training RNN network.

**Comment by jzi040941** [comment]
will update README based on new run.sh file too

**Comment by zoulingqi** [comment]
"train_length_size is the same as sequence size when you training RNN network." if i have 9 wavs,and each wav should have the same length,like 1 second.Because 10ms generates 70 features,I get 9x100x70 feature and train_length_size should be 100.Am i right?

**Comment by jzi040941** [comment]
Yes, your answer is right!

**Comment by zoulingqi** [comment]
Thank you so much!
