### ISSUE TITLE
problem about calculation of Pitch

### ISSUE THREAD

**Issue by zoulingqi** [jzi040941/PercepNet#32]
Hi,
In your code:
float T = noisy->last_period/(PITCH_MAX_PERIOD-3*PITCH_MIN_PERIOD),this make T either 1 or 0.

float T = (float)noisy->last_period/(PITCH_MAX_PERIOD-3*PITCH_MIN_PERIOD) can make T right.

**Comment by jzi040941** [comment]
Thank you for your report. it was my mistake
