### ISSUE TITLE
Macro `FRAME_LOOKAHEAD` maybe error

### ISSUE THREAD

**Issue by TeaPoly** [jzi040941/PercepNet#38]
https://github.com/jzi040941/PercepNet/blob/2d60441617235ac5a819debb31800e51d676879b/src/denoise.cpp#L29

`FRAME_LOOKAHEAD` is 3 if it equal to `round(PITCH_MAX_PERIOD*COMB_M/WINDOW_SIZE + 0.5)`, because `PITCH_MAX_PERIOD=768`, `COMB_M=3`, `WINDOW_SIZE=960`.

**Comment by jzi040941** [comment]
Yes, the comment was wrong WINDOW_SIZE should change to FRAME_SIZE.
