### ISSUE TITLE
Data Creater(c++) for pytorch

### ISSUE THREAD

**Issue by JiachuanDENG** [jzi040941/PercepNet#4]
Hi jzi040941! Thanks for sharing your code with us! 
But may I ask where can I find the code for ***Data Creater(c++) for pytorch***?

**Comment by jzi040941** [comment]
hello JiachuanDENG, main.cpp, denoise.cpp are c++ code related to Data creator
here I write briefly how to create data for training. (will add more detail information about preparing data and training on README file on this weekend)

first, you need to create main binary file
```
g++ *.cpp *.h -o main
```

second, 
main <speech.pcm> <noise.pcm> <data_n> <outputfilename>
for example, I use sample pcm file on sampledata folder that I get it from VCTK, DEMAND dataset.
```
main sampledata/speech/speech.pcm sampledata/noise/noise.pcm 4000, test.output
```

third, 
convert this binary file to hdf5 format file using bintoh5test.ipynb (this ipynb is quite dirty now.. if you can improve more feel free to make pull request)
based on binto5test.ipynb it will generate **h5.training** file.

as you know this repo is unofficial and still on progress also side project for me. It might have problem, make issue or create pull request If you find any weird thing or can make improve

**Comment by JiachuanDENG** [comment]
> hello JiachuanDENG, main.cpp, denoise.cpp are c++ code related to Data creator
> here I write briefly how to create data for training. (will add more detail information about preparing data and training on README file on this weekend)
> 
> first, you need to create main binary file
> 
> ```
> g++ *.cpp *.h -o main
> ```
> 
> second,
> main <speech.pcm> <noise.pcm> <data_n>
> for example, I use sample pcm file on sampledata folder that I get it from VCTK, DEMAND dataset.
> 
> ```
> main sampledata/speech/speech.pcm sampledata/noise/noise.pcm 4000 test.output
> ```
> 
> third,
> convert this binary file to hdf5 format file using bintoh5test.ipynb (this ipynb is quite dirty now.. if you can improve more feel free to make pull request)
> based on binto5test.ipynb it will generate **h5.training** file.
> 
> as you know this repo is unofficial and still on progress also side project for me. It might have problem, make issue or create pull request If you find any weird thing or can make improvement

Thanks jzi040941! Let me check it out! Good job!
