### ISSUE TITLE
Out of bound in  compute_frame_features()

### ISSUE THREAD

**Issue by sTarAnna** [jzi040941/PercepNet#5]
Thanks for sharing your code first!
I have run the demo to generate features with the speech and noise pcm files in the sampledata. But I found that the code in  
function _compute_frame_features_
`
  for (k=-COMB_M;k<COMB_M+1; k++){
    for (i=0;i<WINDOW_SIZE;i++)
p[i] += st->comb_buf[COMB_BUF_SIZE-FRAME_SIZE*(COMB_M)-WINDOW_SIZE-pitch_index*k+i]*common.comb_hann_window[k+COMB_M];
  } 
`

may have a out of bound problem. The 
`
COMB_BUF_SIZE-FRAME_SIZE*(COMB_M)-WINDOW_SIZE-pitch_index*k+i
`
could be bigger than COMB_BUF_SIZE during calculating when _pitch_index_ is large enough and k in lower than zero (I have observed that).

Could you please check here and tell me if I have made something wrong.
Thank you again!

**Comment by jzi040941** [comment]
hello @sTarAnna 

Yes, you are right
I defined COMB_BUF_SIZE as FRAME_SIZE*10 + WINDOW_SIZE  (FRAME_SIZE = 480, WINDOW_SIZE = 960) = 5760
according to pitch.cpp and denoise.cpp pitch_index cannot exceed PITCH_MAX_PERIOD which is defined as 768 in denoise.cpp

with current code
FRAME_SIZE*COMB_M+WINDOW_SIZE = 480*3+960 = 2400
let pitch_index as MAX_PITCH_PEROID which is 768 
5760 - 2400 - 768*(-3) = 5664 

with condition increasing i in for loop  5664 + 960 > 5760 so it occur out of bound error

```
COMB_BUF_SIZE-FRAME_SIZE*(COMB_M)-WINDOW_SIZE-pitch_index*k+i
```
this need change to
```
COMB_BUF_SIZE-FRAME_SIZE*FRAME_LOOKAHEAD-WINDOW_SIZE-pitch_index*k+i
```

but still need to sync P[i] with frame_analysis of input  on line 312 denoise.cpp
I append it later soon.

Thanks!
