### ISSUE TITLE
How to train and infer model with sampleData

### ISSUE THREAD

**Issue by tungedng2710** [jzi040941/PercepNet#53]
Hi, I'm struggling with your code. I can't train the model with your given sampleData. There are the steps I have done
1. clone your repository
2. Download the sampleData (VTCK for speech and DEMAND for noise), then I copied all audio files (.wav) to ```speech``` and ```noise``` folder 
3. _Make binary directory, build_, do _feature generation_ and _convert output binary to h5_ following your README instruction.  
4. run the ```run.sh``` script in the ```utils``` folder.

However, it raises the FileNotFoundError:  No such file or directory: '/home/myname/code/PercepNet/utils/../training_set_sept12_500h/features/**train.txt**'
I also tried to create this file manually via running **split_feature_dataset.py** with the path to the sampledata directory, it then generated 2 blank files train.txt and dev.txt. Whats wrong I have done? Thank you.

**Comment by jzi040941** [comment]
hi ,
sorry for confusing you. at the first time when I tried to implement PercepNet I used VTCK and DEMAND.
but after few moments I found that there's `DNS-challange` dataset and it can  synthesize noisy file depending on configuration.
you should use DNS-challenge 500h synthesized dataset to use `run.sh`
https://github.com/microsoft/DNS-Challenge

**Comment by tungedng2710** [comment]
Thank you!

**Comment by LeventureQys** [comment]
stage=4     #stage to start
stop_stage=4 #stop stage

utils/run.sh
switch the stage = 4 to stage = 1
