### ISSUE TITLE
Reading file error in train()

### ISSUE THREAD

**Issue by sTarAnna** [jzi040941/PercepNet#6]
On Windows platform.
In denoise.cpp, train()
`
f1 = fopen(argv[1], "r");  
f2 = fopen(argv[2], "r");  
`
is used to read noise and speech file (pcm or raw). But the mode should be set to 'rb'.

`
f1 = fopen(argv[1], "rb");  
f2 = fopen(argv[2], "rb");  
`

**Comment by jzi040941** [comment]
Nice, I didn't know that this is not working in Windows
I fixed it!

**Comment by sTarAnna** [comment]
On windows platf
