### ISSUE TITLE
Saving test file and transform to .wav

### ISSUE THREAD

**Issue by sTarAnna** [jzi040941/PercepNet#9]
Hi, I have run your latest code and generated the output file.
Then i use _sox_ to transform the 16bit pcm output file to wav file with 48kHz sample rate.
The transformed enchanced signal sounds not good. To furthur find the reason, i send the stft of clean speech **X** to frame_synthesis() function and generate a clean speech with stft and istft operation only. I transform it to the wav with same operation and it still sounds not good. So i do a simple test which ignores the zeros frames generated in the first 6 steps, and the wav file sounds good. So I suggest you to add 
`
if(count>5)
`
 before saving the calculated features and output files.

Thanks!

**Comment by sTarAnna** [comment]
Experiment error, sorry for disturbing you!

**Comment by jzi040941** [comment]
It's okay! very thankful for experimenting my code

**Comment by jzi040941** [comment]
I have one thing let you know the result of ideal filtered output is still not good.

one reason for bad filter quality I guess it is because of interp_band_gain function error
the expected result is like below
input g={1,1,1,1,.....,1,1,1} output gf={0,0,.,1,1,1,1,1,1,1,....,0,0,0} 
cause if band gain is 1 than stft_freq_gain must be 1 too.

but result of function is not like that I write above.
finding solution now

**Comment by jzi040941** [comment]
I changed ERBBand calculation could you check for result?

**Comment by sTarAnna** [comment]
> I changed ERBBand calculation could you check for result?

I just want to tell you my result, lol. Today I changed the erb band part back to the rnnoise with insert extra bands in the low frequency to increase the aomount of bands, then I found it works well.

I would check for result now! Thank you!

**Comment by sTarAnna** [comment]
> I changed ERBBand calculation could you check for result?

I have run your latest code with the data from https://www.amazon.science/blog/how-amazon-chimes-challenge-winning-noise-cancellation-works, it sounds perfect!

**Comment by jzi040941** [comment]
Wow, Thanks I'm gonna do next step!
